# Generated by Django 2.2.19 on 2021-07-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='startDate',
            field=models.DateField(),
        ),
    ]
